[tools]
python = "3.13.7"
uv = "0.8"
"pipx:ruff" = "latest"

[tasks.dev-backend]
run = ["uv run python ./backend/main.py"]

[tasks.dev-frontend]
run = ["uv run python -m http.server -d ./frontend 8889"]
